from typing import List, Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The user query or question to be answered by the assistant",
        examples=["What is a Python dictionary and how do you create one?"],
    )


class QueryResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The grounded answer generated by the assistant",
    )
    sources: List[str] = Field(
        default_factory=list,
        description="List of cited source documents and page references",
        examples=[["Introduction_to_Python_Programming-WEB.pdf, p.125"]],
    )


class HealthResponse(BaseModel):
    status: str = Field(default="ok", description="Service health status")
    vector_store_loaded: bool = Field(..., description="Whether vector store is ready")
    ollama_connected: bool = Field(..., description="Whether Ollama LLM endpoint is reachable")
    model: str = Field(..., description="Active Ollama model name")
    collection: Optional[str] = Field(None, description="Active Chroma collection name")
